@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

echo ========================================
echo   ULTIMATEUNBLOCKER - ENV CREATOR
echo ========================================
echo.
echo This script will help you create a .env file
echo with all necessary API keys for the application.
echo.
echo Press Ctrl+C to cancel at any time.
echo.
pause
cls

echo ========================================
echo   API KEY COLLECTION
echo ========================================
echo.

REM Check if .env already exists
if exist .env (
    echo WARNING: .env file already exists!
    echo.
    set /p overwrite="Do you want to overwrite it? (Y/N): "
    if /i "!overwrite!" neq "Y" (
        echo.
        echo Operation cancelled. Existing .env file preserved.
        pause
        exit /b
    )
    echo.
    echo Backing up existing .env to .env.backup...
    copy .env .env.backup >nul
    echo Backup created.
    echo.
)

REM Collect API keys - no defaults, users must enter their own
echo [1/16] OpenRouter API Key (API)
set /p API="Enter your OpenRouter API key (or press Enter to skip): "

echo [2/16] HuggingFace API Key (API2)
set /p API2="Enter your HuggingFace API key (or press Enter to skip): "

echo [3/16] LockLLM API Key (API3)
set /p API3="Enter your LockLLM API key (or press Enter to skip): "

echo [4/16] Groq API Key (API4)
set /p API4="Enter your Groq API key (or press Enter to skip): "

echo [5/16] Cloudflare API Key (API5)
set /p API5="Enter your Cloudflare API key (or press Enter to skip): "

echo [6/16] Google AI Studio API Key (API6)
set /p API6="Enter your Google AI Studio API key (or press Enter to skip): "

echo [7/16] GitHub Personal Access Token (API7)
set /p API7="Enter your GitHub PAT (or press Enter to skip): "

echo [8/16] Emergent AI API Key (API8)
set /p API8="Enter your Emergent AI API key (or press Enter to skip): "

echo [9/16] Spotify Client ID
set /p SPOTIFY_CLIENT_ID="Enter your Spotify Client ID (or press Enter to skip): "

echo [10/16] Spotify Client Secret
set /p SPOTIFY_CLIENT_SECRET="Enter your Spotify Client Secret (or press Enter to skip): "

echo [11/16] Jamendo Client ID
set /p JAMENDO_CLIENT_ID="Enter your Jamendo Client ID (or press Enter to skip): "

echo [12/16] YouTube API Key
set /p YOUTUBE_API_KEY="Enter your YouTube API Key (or press Enter to skip): "

echo [13/16] YouTube API Key 2 (Backup)
set /p YOUTUBE_API_KEY_2="Enter your YouTube API Key 2 (or press Enter to skip): "

echo [14/16] Merriam Webster API Key
set /p MERRIAM_WEBSTER_API_KEY="Enter your Merriam Webster API Key (or press Enter to skip): "

echo [15/16] Cloudflare Account ID
set /p CLOUDFLARE_ACCOUNT_ID="Enter your Cloudflare Account ID (or press Enter to skip): "

echo [16/16] Cloudflare Gateway ID
set /p CLOUDFLARE_GATEWAY_ID="Enter your Cloudflare Gateway ID (or press Enter to skip): "

echo.
echo ========================================
echo   CREATING .ENV FILE
echo ========================================
echo.

REM Create .env file
(
    echo # ULTIMATEUNBLOCKER Environment Variables
    echo # Generated by env_creator.bat on %date% at %time%
    echo.
    echo # API Keys
    if defined API echo API=!API!
    if not defined API echo API=your_openrouter_key_here
    if defined API2 echo API2=!API2!
    if not defined API2 echo API2=your_huggingface_key_here
    if defined API3 echo API3=!API3!
    if not defined API3 echo API3=your_lockllm_key_here
    if defined API4 echo API4=!API4!
    if not defined API4 echo API4=your_groq_key_here
    if defined API5 echo API5=!API5!
    if not defined API5 echo API5=your_cloudflare_api_key_here
    if defined API6 echo API6=!API6!
    if not defined API6 echo API6=your_google_ai_studio_key_here
    if defined API7 echo API7=!API7!
    if not defined API7 echo API7=your_github_pat_here
    if defined API8 echo API8=!API8!
    if not defined API8 echo API8=your_emergent_api_key_here
    if defined SPOTIFY_CLIENT_ID echo SPOTIFY_CLIENT_ID=!SPOTIFY_CLIENT_ID!
    if not defined SPOTIFY_CLIENT_ID echo SPOTIFY_CLIENT_ID=your_spotify_client_id_here
    if defined SPOTIFY_CLIENT_SECRET echo SPOTIFY_CLIENT_SECRET=!SPOTIFY_CLIENT_SECRET!
    if not defined SPOTIFY_CLIENT_SECRET echo SPOTIFY_CLIENT_SECRET=your_spotify_client_secret_here
    if defined JAMENDO_CLIENT_ID echo JAMENDO_CLIENT_ID=!JAMENDO_CLIENT_ID!
    if not defined JAMENDO_CLIENT_ID echo JAMENDO_CLIENT_ID=your_jamendo_client_id_here
    if defined YOUTUBE_API_KEY echo YOUTUBE_API_KEY=!YOUTUBE_API_KEY!
    if not defined YOUTUBE_API_KEY echo YOUTUBE_API_KEY=your_youtube_api_key_here
    if defined YOUTUBE_API_KEY_2 echo YOUTUBE_API_KEY_2=!YOUTUBE_API_KEY_2!
    if not defined YOUTUBE_API_KEY_2 echo YOUTUBE_API_KEY_2=your_youtube_api_key_2_here
    if defined MERRIAM_WEBSTER_API_KEY echo MERRIAM_WEBSTER_API_KEY=!MERRIAM_WEBSTER_API_KEY!
    if not defined MERRIAM_WEBSTER_API_KEY echo MERRIAM_WEBSTER_API_KEY=your_merriam_webster_api_key_here
    echo.
    echo # Cloudflare Workers AI
    if defined CLOUDFLARE_ACCOUNT_ID echo CLOUDFLARE_ACCOUNT_ID=!CLOUDFLARE_ACCOUNT_ID!
    if not defined CLOUDFLARE_ACCOUNT_ID echo CLOUDFLARE_ACCOUNT_ID=your_cloudflare_account_id_here
    if defined CLOUDFLARE_GATEWAY_ID echo CLOUDFLARE_GATEWAY_ID=!CLOUDFLARE_GATEWAY_ID!
    if not defined CLOUDFLARE_GATEWAY_ID echo CLOUDFLARE_GATEWAY_ID=your_cloudflare_gateway_id_here
    echo.
    echo # Server Configuration
    echo PORT=3000
    echo NODE_ENV=production
    echo DEBUG=false
    echo.
    echo # Discord Integration
    echo DISCORD_SERVER_ID=1487910769776394343
    echo DISCORD_CHANNEL_ID=1487951675057508444
    echo DISCORD_INVITE_URL=https://discord.gg/PpbddfffVT
    echo.
    echo # Database (Optional)
    echo DATABASE_URL=mongodb://localhost:27017/ultimateunblocker
    echo REDIS_URL=redis://localhost:6379
    echo.
    echo # Security
    echo JWT_SECRET=your_jwt_secret_here_change_this
    echo ENCRYPTION_KEY=your_encryption_key_here_change_this
    echo.
    echo # Features
    echo ENABLE_AI=true
    echo ENABLE_PROXY=true
    echo ENABLE_CHAT=true
    echo ENABLE_GAMING=true
    echo.
    echo # Performance
    echo CACHE_TTL=3600
    echo RATE_LIMIT=100
    echo MAX_CONNECTIONS=1000
) > .env

echo.
echo ========================================
echo   SUCCESS!
echo ========================================
echo.
echo .env file has been created successfully!
echo.
echo IMPORTANT: 
echo - Do NOT commit .env to GitHub
echo - Add .env to your .gitignore file
echo - Keep your API keys secure
echo.
echo Next steps:
echo 1. Review the .env file
echo 2. Deploy your application
echo 3. The .env file will be used automatically
echo.
pause
